apiVersion: v1
kind: Pod
metadata:
  name: event-bus-publisher-ms
  labels:
    app: event-bus-publisher-ms
spec:
  nodeName: minikube
  containers:
  - name: event-bus-publisher
    # get latest version of image
    image: lucasjellema/node-app-runner
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: "https://github.com/lucasjellema/microservices-choreography-kubernetes-workshop-june2017"
    - name: APP_PORT
      value: "8096"
    - name: APP_HOME
      value: "part3/event-bus-publisher"
    - name: APP_STARTUP
      value: "EventBusPublisher.js"
    - name: KAFKA_HOST
      value: "ubuntu"
    - name: ZOOKEEPER_PORT
      value: "2181"
    - name: KAFKA_TOPIC
      value: "event-bus"
    ports:
    # containerPort is the port exposed by the container (where nodejs express api is listening)
    - containerPort: 8096
    lifecycle:
      postStart:
        exec:
          # add advertised host (ubuntu) of VM running Kafka to hosts file - with that VMs network interface's IP address
          command: ["sh","-c","echo 192.168.188.101 ubuntu > /etc/hosts"]
